### ISSUE TITLE
Make it possible to define how many collections are shown pr category 

### ISSUE THREAD

**Issue by lfrostp** [jl94x4/ColleXions#7]
Would it be possible to define number of collections shown pr category instead of library?
It would add more control over your homepage. 
`
"Category 1": 
    "number_of_collections_to_pin":  1,
    "Collections": [
        "Action Movies",
        "Western Movies",
        "Thriller Movies"
]
`

**Comment by jl94x4** [comment]
I've had a little look into this, and I think the word you are looking for is genre's instead of categories, however due to the way collections work, they don't actually have a genre associated to them, so there is no way that ColleXions could determine what genre a single collection would correspond to. It makes this request almost impossible to implement.

You can look at categories, which I think is something that could work for you and would more than likely solve your issue.

**Comment by lfrostp** [comment]
@jl94x4 hmm it close but not entirely the purpose , i can give you an example of how i would use it.
I would "categories" 3-5 universes(marvel etc.) and get it to select 1 of them. I would do the same with streaming services and decades as categories. That way i would always have 1 of my categories but rotate 3-5 different.

**Comment by jl94x4** [comment]
> @jl94x4 hmm it close but not entirely the purpose , i can give you an example of how i would use it. I would "categories" 3-5 universes(marvel etc.) and get it to select 1 of them. I would do the same with streaming services and decades as categories. That way i would always have 1 of my categories but rotate 3-5 different.

This is already implemented via the categories part of the config 🙂
